### ISSUE TITLE
add documentation to 'spiders' directory

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings.crawler#2]
Low-ish priority, but it would be nice to add a README to https://github.com/biothings/biothings.crawler/tree/master/crawler/spiders to explain the difference between broadscrape, focusedscrape, and sitemapscrape

**Comment by namespacestd0** [comment]
Added here https://github.com/biothings/biothings.crawler#spiders

**Comment by andrewsu** [comment]
looks great!
